In [37]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model

In [43]:
data = pd.read_csv('student_dataset/student-mat.csv',sep= ";")
data.shape

(395, 33)

In [44]:
data.head(5)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [45]:
data = data[["G1","G2","G3","studytime","failures","absences"]]
data.head()

G1  G2  G3  studytime  failures  absences
0   5   6   6          2         0         6
1   5   5   6          2         0         4
2   7   8  10          2         3        10
3  15  14  15          3         0         2
4   6  10  10          2         0         4

In [41]:
data.shape

(394, 33)

In [42]:
predict = "G3" #label

In [46]:
X = np.array(data.drop([predict], 1))
y = np.array(data[predict])

In [47]:
print (X)

[[ 5  6  2  0  6]
 [ 5  5  2  0  4]
 [ 7  8  2  3 10]
 ...
 [10  8  1  3  3]
 [11 12  1  0  0]
 [ 8  9  1  0  5]]


In [48]:
x_train, x_test,y_train,y_test =  sklearn.model_selection.train_test_split(X,y,test_size = 0.1)

In [49]:
 linear = linear_model.LinearRegression() 

In [50]:
linear.fit(x_train, y_train)
acc = linear.score(x_test,y_test)
print (acc)

0.8070288505559577


In [55]:
print('Coefficient: ', linear.coef_)
print('Intercept: ', linear.intercept_)


Coefficient:  [ 0.1281596   0.99043303 -0.1600954  -0.4012944   0.03214963]
Intercept:  -1.329434955067354


In [56]:
predictions = linear.predict(x_test)

In [57]:
for x in range (len(predictions)):
    print (predictions[x],x_test[x],y_test[x])

16.183995957351193 [15 16  2  0  2] 16
11.966822463491946 [11 12  2  0 10] 13
11.997869168841303 [15 12  3  0  0] 14
3.5429208134366794 [3 5 2 1 8] 5
6.288568754651413 [ 7  8  2  3 10] 10
16.312155553403976 [16 16  2  0  2] 17
7.508224880875632 [ 9  8  2  1 15] 8
12.892078412156517 [13 13  2  0  0] 13
8.032411525007264 [9 9 1 2 8] 9
7.555434460871751 [10  8  2  0  0] 9
9.248045527274028 [ 9 10  3  0  0] 0
17.784394085754954 [17 17  2  0 13] 17
12.892078412156517 [13 13  2  0  0] 12
4.071935893158492 [5 5 2 0 4] 6
5.3186881178893435 [7 6 2 0 4] 6
11.325360475344477 [ 9 12  3  0  3] 11
11.778160642673546 [14 11  1  0 18] 13
19.032024139233258 [17 18  2  0 21] 18
17.04625812127778 [17 17  4  0  0] 18
6.052363044035328 [6 7 2 0 0] 0
15.12970258388638 [14 15  2  0  4] 15
18.22872236344128 [16 18  2  0  0] 19
11.869720845434422 [11 12  1  0  2] 11
12.635808191873869 [15 13  3  2 14] 13
5.510933148291473 [7 6 1 0 5] 7
6.133313060091996 [ 6  7  2  1 15] 8
11.837785038691706 [12 12  2  0  2] 11